# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b31c0593eaa56f011f8dabea340a19b19ab7cace98f6e2cd4b32508d65a5418971aab21202e47be3c56045cc87493fa14301cf0aa1ad52d909fa495d55427792

test:
  secret_key_base: 4773406ae55e1f421017d3045cb8dea21d56eb0caf170acd4da8a7857ebe44ee8baaaa74fc0cd8fb9763e4579a3ca5f635d41492f73e3ba463adf99b9deba357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
